devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    
    path('', views.projects, name="prod"),
    path('project/<str:pk>/', views.project, name="project"),

    path('create-project/', views.createProject, name="create-project"),
     path('delete-project/<str:pk>/', views.deleteProject, name="delete-project"),
    path('update-project/<str:pk>/', views.updateProject, name="update-project"),
]

users/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

urlpatterns = [
   path('', views.profiles, name="profiles"),
   path('profile/<str:pk>/', views.userProfile, name="user-profile"),
   
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=2000, unique=True)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False) 

    def __str__(self):
       return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )

    #owner =
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body =  models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value

class Tag(models.Model):
      name = models.CharField(max_length=200)
      created = models.DateTimeField(auto_now_add=True)
      id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

      def __str__(self):
          return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png" )
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False) 

    def __str__(self):
        return str(self.user.username)

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False) 

    def __str__(self):
        return str(self.name)

projects/forms.py
from django.forms import ModelForm, fields
from .models import Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

projects/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Project
from .forms import ProjectForm

def projects(request):
    projects = Project.objects.all()
    context = {'projects': projects}
    return render(request,'projects/projects.html', context)

def project(request,pk):
    projectObj = Project.objects.get(id=pk)
    return render(request,'projects/single-project.html',{'project': projectObj})

def createProject(request):
    form = ProjectForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('prod')
    context = {'form': form}
    return render(request,'projects/project_form.html', context)


def updateProject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('prod')
    context = {'form': form}
    return render(request,'projects/project_form.html', context)


def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('prod')
    context = {'object':project}
    return render(request, 'projects/delete_templates.html', context)

 

users/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles':profiles}
    return render(request, 'users/profiles.html', context)

def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    context = {'profile':profile}
    return render(request, 'users/user-profile.html', context)

projects/templates/projects/delete_templates.html
{% extends 'main.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <p>Are You Sure You want to delete "{{object}}"?</p>
     <a href="{% url 'prod' %}">Go Back</a>
    <input type="submit" value="Confirm"/>
</form>

{% endblock %}

projects/templates/projects/project_form.html
{% extends 'main.html' %}
{% block content %}

<hi> Project Form</hi>

<form action="" method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" />
</form>

{% endblock %} 

projects/templates/projects/projects.html
{% extends 'main.html' %}

{% block content %}




<main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>
        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
            {% for project in projects %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'project' project.id %}" class="project">
                <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{project.title}}</h3>
                  <p><a class="project__author" href="{% url 'project' project.id %}">By {{project.owner.name}}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{project.vote_total}}%</span> Positive
                    Feedback ({{project.vote_ratio}} Vote{{project.vote_total|pluralize:"s"}})
                  </p>                  
                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{tag}}</small>
                    </span>
                    {% endfor %}
                 
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}

          

        </div>
      </div>
    </section>


  </main>

{% endblock content %}

projects/templates/projects/single-project.html
{% extends 'main.html' %}

{% block content %}


<img style="max-width: 500px" src="{{project.featured_image.url}}">


<h1>{{project.title}}</h1>
<p>{{project.description}}</p>
{% for tag in project.tags.all %}
<small>{{tag}}</small>

{% endfor %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="uikit/styles/uikit.css" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="styles/app.css" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Nodejs</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Express</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>GraphQL</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/1868782" alt="image" />
                  <div class="dev__meta">
                    <h3>Cody Seibert</h3>
                    <h5>React Developer, Coding Youtuber</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>Elixir</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>F#</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>.NET</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/33843378" alt="image" />
                  <div class="dev__meta">
                    <h3>Dennis Ivy</h3>
                    <h5>Python & Django Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>Python</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Django</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>Rest API</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
          <div class="column card">
            <div class="dev">
              <a href="/profile.html" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="https://avatars.githubusercontent.com/u/22437186" alt="image" />
                  <div class="dev__meta">
                    <h3>Shahriar P. Shuvo</h3>
                    <h5>FullStack Web Designer & Developer</h5>
                  </div>
                </div>
                <p class="dev__info">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate, ducimus inventore! Sunt,
                  veniam veritatis? Veritatis placeat, deleniti iure tempore veniam perspiciatis, soluta cupiditate
                  animi, exercitationem molestias nam doloremque architecto odit.
                </p>
                <div class="dev__skills">
                  <span class="tag tag--pill tag--main">
                    <small>JavaScript</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>React</small>
                  </span>
                  <span class="tag tag--pill tag--main">
                    <small>SCSS</small>
                  </span>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>
</body>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <title>DevSearch - Connect with Developers!</title>
</head>
<body>
    {%include 'navbar.html'%}
    
    {% block content %}
    
    {% endblock content%}

</body>
</html>

templates/navbar.html
{% load static %}

 <!-- Header Section -->
 <header class="header">
    <div class="container container--narrow">
      <a href="{% url 'profiles' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'profiles' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'prod' %}">Projects</a></li>
          <li class="header__menuItem"><a href="">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'create-project' %}">Add Project</a></li>
          <li class="header__menuItem"><a href="" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

          {% for profile in profiles %}  
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro}}</h5>
                  </div>
                </div>
                <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                <div class="dev__skills">

                {% for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                {% endfor %}
                  
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </section>

    <div class="pagination">

    </div>
  </main>

{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                <li>
                  <a title="Stackoverflow" href="#" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>




            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}